"""add_vetis_auth_data

Revision ID: 2266315fdedf
Revises: bcfbc4976ba8
Create Date: 2023-06-02 21:12:04.728372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2266315fdedf'
down_revision = 'bcfbc4976ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vetis_auth_data',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('enterprise_login', sa.String(), nullable=True),
    sa.Column('enterprise_password', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('issuer_id', sa.String(), nullable=True),
    sa.Column('user_login', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_vetis_auth_data_uuid'), 'vetis_auth_data', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vetis_auth_data_uuid'), table_name='vetis_auth_data')
    op.drop_table('vetis_auth_data')
    # ### end Alembic commands ###
