"""add enterprise model

Revision ID: 32b9afc23188
Revises: 71ac16df57ae
Create Date: 2023-06-21 16:15:09.858605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b9afc23188'
down_revision = '71ac16df57ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('enterprise_uuid', sa.String(), nullable=True),
    sa.Column('business_entity_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_enterprise_uuid'), 'enterprise', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterprise_uuid'), table_name='enterprise')
    op.drop_table('enterprise')
    # ### end Alembic commands ###
