"""delete organization

Revision ID: 71ac16df57ae
Revises: f14efa0bb274
Create Date: 2023-06-20 16:16:57.886733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ac16df57ae'
down_revision = 'f14efa0bb274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checked_document', 'organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_document', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
