"""uuid to guid

Revision ID: a3108cf85009
Revises: 32b9afc23188
Create Date: 2023-06-22 23:42:32.832271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3108cf85009'
down_revision = '32b9afc23188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('enterprise_guid', sa.String(), nullable=True))
    op.add_column('enterprise', sa.Column('business_entity_guid', sa.String(), nullable=True))
    op.drop_column('enterprise', 'enterprise_uuid')
    op.drop_column('enterprise', 'business_entity_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('business_entity_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('enterprise_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('enterprise', 'business_entity_guid')
    op.drop_column('enterprise', 'enterprise_guid')
    # ### end Alembic commands ###
