"""update_vetis_auth_data

Revision ID: bea73385af89
Revises: 2266315fdedf
Create Date: 2023-06-04 02:35:39.797395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea73385af89'
down_revision = '2266315fdedf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vetis_auth_data', sa.Column('initiator', sa.String(), nullable=True))
    op.drop_constraint('vetis_auth_data_user_uuid_fkey', 'vetis_auth_data', type_='foreignkey')
    op.create_foreign_key(None, 'vetis_auth_data', 'user', ['user_login'], ['login'], ondelete='CASCADE')
    op.drop_column('vetis_auth_data', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vetis_auth_data', sa.Column('user_uuid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vetis_auth_data', type_='foreignkey')
    op.create_foreign_key('vetis_auth_data_user_uuid_fkey', 'vetis_auth_data', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('vetis_auth_data', 'initiator')
    # ### end Alembic commands ###
