"""add_document_model

Revision ID: dffb20929065
Revises: bea73385af89
Create Date: 2023-06-04 20:51:24.321413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffb20929065'
down_revision = 'bea73385af89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_document',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('vet_document_uuid', sa.String(), nullable=True),
    sa.Column('is_mistakes', sa.Boolean(), nullable=True),
    sa.Column('person', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_checked_document_uuid'), 'checked_document', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checked_document_uuid'), table_name='checked_document')
    op.drop_table('checked_document')
    # ### end Alembic commands ###
